version: '3.1'
services:
  master:
    image: mysql:1
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234*
    volumes:
      - /docker/mysql/master:/var/lib/mysql
  slave:
    image: mysql:2
    ports:
      - '3307:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234*
    volumes:
      - /docker/mysql/slave:/var/lib/mysql
